#!/usr/bin/env bash
#  A Script that configures a new Ubuntu machine

# Step 1: Install Nginx (if not already installed)
sudo apt-get update
sudo apt-get install nginx -y

# Step 2: Configure Nginx for redirection
sudo sh -c 'echo "server {
    listen 80;
    server_name localhost;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    # Add other server configurations if needed

}" > /etc/nginx/sites-available/redirect_me'

# Step 3: Create a symbolic link to enable the site
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled

# Step 4: Test Nginx configuration
sudo nginx -t

# Step 5: Reload Nginx to apply changes
sudo systemctl reload nginx
