#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80
awk '{gsub(/80/, "8080")}1' /etc/nginx/nginx.conf > /tmp/nginx.conf.tmp && mv /tmp/nginx.conf.tmp /etc/nginx/nginx.conf
service nginx restart
