#!/bin/bash

sed -i 's/user\snginx;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen\s80;/listen 8080;/g' /etc/nginx/sites-available/default
service nginx restart
ps auxff | grep '[n]ginx'
nc -z 0 8080
